plugins:
  tslint:
    enabled: true
    config: ./projects/kalidea/kaligraphi/tslint.json

exclude_patterns:
  - coverage
  - dist
  - e2e
  - node_modules
  - scripts
  - src
  - projects
  - "**/*.spec.ts"
  - "!projects/kalidea/kaligraphi/src"
