version: "2"

checks:
  method-complexity:
    config:
      threshold: 7
  method-count:
    config:
      threshold: 35
  file-lines:
    config:
      threshold: 500

plugins:
  tslint:
    enabled: true
    config: tslint.json
  duplication:
    enabled: true
    config:
      languages:
        typescript:
          mass_threshold: 75

exclude_patterns:
  - coverage
  - dist
  - e2e
  - node_modules
  - scripts
  - src
  - "**/*.spec.ts"
  - "**/*.js"
  - "**/test.ts"
