version: "2"
plugins:
  tslint:
    enabled: true
    config: tslint.json

exclude_patterns:
  - coverage
  - dist
  - e2e
  - node_modules
  - scripts
  - src
  - "**/*.spec.ts"
  - "**/*.js"
  - "**/test.ts"

engines:
  duplication:
    enabled: true
    config:
      languages:
        typescript:
          mass_threshold: 75
