version: "2"

checks:
  method-complexity:
    config:
      threshold: 7
  file-lines:
    config:
      threshold: 500

plugins:
  tslint:
    enabled: true
    config: tslint.json

exclude_patterns:
  - coverage
  - dist
  - e2e
  - node_modules
  - scripts
  - src
  - "**/*.spec.ts"
  - "**/*.js"
  - "**/test.ts"
