name: CI

# trigger this build on push & pull_request
on:
  push:
    branches:
      - master
      - 'releases_v*' # release for version X
  pull_request:
    branches:
      - master
      - 'releases/**'

env:
  NODE_RELEASE_VERSION: 20 # release version created by NODE 10

jobs:
  test-and-build:
    name: Test and Build
    # Run only on pull_request
    runs-on: ubuntu-latest
    # run this workflow on multiple node version
    strategy:
      matrix:
        node: [20]
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set node version
        uses: actions/setup-node@v1
        with:
          node-version:  ${{ matrix.node }}

      - name: Install dependencies
        run: |
          npm i

      - name: Lint code
        run: npm run lint

      - name: Run test suite
        run: npm run test:ci

      - name: Build Lib & Playground
        run: |
          npm run build:lib
          npm run build:playground -- --base-href /kaligraphi/

      - name: Upload to Github Pages
        # deploy only once to GitHub page
        if: matrix.node == env.NODE_RELEASE_VERSION
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist/playground # The folder the action should deploy.

  deploy:
    needs: test-and-build
    name: Deploy package
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'kalidea/releases')
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set node version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_RELEASE_VERSION }}

      - name: Tag version
        run: |
          echo "get version"
          cd ./projects/kalidea/kaligraphi
          version=`npm view @kalidea/kaligraphi version`
          cd ../../../

      - name: Build library
        run: |
          npm i
          npm run build
          cp README.md dist/kalidea/kaligraphi/

      - name: Set REGISTRY NPMJS
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_RELEASE_VERSION }}
          registry-url: 'https://registry.npmjs.org'

      - name: Deploy to NPMJS
        run: |
          cd dist/kalidea/kaligraphi
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}

      - name: Set REGISTRY github
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_RELEASE_VERSION }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@kalidea'

      - name: Deploy to github package
        run: |
          cd dist/kalidea/kaligraphi
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
